# Generated by Django 3.1 on 2020-08-07 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='имя автора')),
                ('birth_year', models.SmallIntegerField(verbose_name='год рождения')),
                ('country', models.CharField(max_length=2, verbose_name='страна')),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_name', models.CharField(max_length=100, verbose_name='имя друга')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_name', models.CharField(max_length=100, verbose_name='название издательства')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=13, verbose_name='международный книжный номер')),
                ('title', models.TextField(verbose_name='название книги')),
                ('description', models.TextField(verbose_name='описание книги')),
                ('year_release', models.SmallIntegerField(verbose_name='год издания')),
                ('copy_count', models.SmallIntegerField(default=1, verbose_name='количество копий')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена')),
                ('book_image', models.ImageField(blank=True, upload_to='', verbose_name='изображение книги')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='p_library.author', verbose_name='автор книги')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_books', to='p_library.publisher', verbose_name='издательство')),
                ('took_copy', models.ManyToManyField(to='p_library.Friend', verbose_name='одолжен экземпляр книги')),
            ],
        ),
    ]
