# Generated by Django 3.1 on 2020-08-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0004_auto_20200808_0008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterModelOptions(
            name='friend',
            options={'verbose_name': 'Друг', 'verbose_name_plural': 'Друзья'},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'verbose_name': 'Издательство', 'verbose_name_plural': 'Издательства'},
        ),
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.ImageField(blank=True, null=True, upload_to='book_images/', verbose_name='изображение книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='took_copy',
            field=models.ManyToManyField(blank=True, related_name='borrowed_books', to='p_library.Friend', verbose_name='взят экземпляр книги'),
        ),
    ]
